# Generated by Django 2.0.4 on 2018-04-30 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180405_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='imageBase64',
            field=models.CharField(default='empty', max_length=5000),
        ),
    ]
