# Generated by Django 2.0.4 on 2018-04-30 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_viaje_imagebase64'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='contact_number',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
